[nats]
url = "nats://localhost:4222"

[nats.streams]
account_stream_name = "accounts"
slot_stream_name = "slots"
transaction_stream_name = "transactions"
entry_stream_name = "entries"
block_metadata_stream_name = "blockmeta"

# Optional: plugin-specific config in a separate file, e.g. config_plugin.toml
